# This is a basic workflow to help you get started with Actions

name: Deploy html to s3

# Controls when the workflow will r
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name:  checkout code from repo
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key-id: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: us-east-1
          
